export const wedding = {
  groom: "Sandeep",
  bride: "Jhansi Lakshmi",
  invocation: "|| Shree Ganeshaya Namah ||",
  eyebrow: "Wedding Invitation",
  tagline: "Two hearts, one journey",
  intro: "Together with our families, invite you to celebrate our wedding",
  date: "27 August 2026",
  dateISO: "2026-08-27",
  time: "Join us from 12:00 PM onwards",
  ceremonyPlace: "At our residency- Bandarulanka",
  muhurtham: "Muhurtham · 11:41 PM",
  muhurthamPlace: "At S.V Function Hall, Rajahmundry",
  couplePhoto: "/images/2BB17DAD-FDA0-4EE9-8AE2-0BBCD301DC72.jpeg",
  blessing: {
    heading: "With hearts full of love and joy,\nwe are delighted to invite you\nto celebrate our wedding with us \u{1F49D}",
    subtext: "Your presence will make our special day even more meaningful and memorable ✨",
  },
  venue: {
    name: "S V Function Hall",
    shortAddress: "Rajahmundry, Andhra Pradesh",
    fullAddress: "S V Function Hall, Rajahmundry, Andhra Pradesh, India",
    mapEmbedUrl: "https://www.google.com/maps?q=S+V+Function+Hall+Rajahmundry&output=embed",
    mapLinkUrl: "https://maps.app.goo.gl/kbzfh9AitBkt3NJVA",
  },
  gallery: [
    { id: 1, alt: "Moment 1", src: "/images/IMG_1250.jpg" },
    { id: 2, alt: "Moment 2", src: "/images/IMG_1252.jpeg" },
    { id: 3, alt: "Moment 3", src: "/images/IMG_1253.jpeg" },
    { id: 4, alt: "Moment 4", src: "/images/IMG_1256.jpeg" },
    { id: 5, alt: "Moment 5", src: "/images/IMG_1257.jpeg" },
    { id: 6, alt: "Moment 6", src: "/images/IMG_1251.jpeg" },
  ],
  footer: {
    couple: "Jhansi Lakshmi & Sandeep",
    date: "27 · 08 · 2026",
    families: "With love, Kudipudi & Gubbala families",
  },
} as const;
